import argparse
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.animation import FuncAnimation
from scipy.integrate import solve_ivp

# Ensure rrt_bridge.py is in the same directory
from rrt_bridge import RRTStarBridge

np.random.seed(42)

# ==========================================
# GLOBAL CONFIGURATION
# ==========================================
ROBOT_RADIUS = 0.35    
GOAL_TOLERANCE = 0.05  

# ==========================================
# 1. EXACT GLOBAL PATH TRACKING
# ==========================================
def get_lookahead_target(pos, path, lookahead=1.0):
    """
    Continuous Pure Pursuit Algorithm.
    Instead of smoothing the entire RRT* path (which cuts corners and loses optimality),
    this strictly tracks the raw line segments. It finds the geometrically closest point 
    on the RRT* path, then projects a 'lookahead' target forward along the segment.
    """
    closest_dist = float('inf')
    target_pt = path[-1]
    
    # Iterate through every line segment generated by RRT*
    for i in range(len(path) - 1):
        seg_start = path[i]
        seg_end = path[i+1]
        
        seg_vec = seg_end - seg_start
        seg_len = np.linalg.norm(seg_vec)
        if seg_len == 0: continue
        seg_dir = seg_vec / seg_len
        
        # Project robot position onto the infinite line of the segment
        v = pos - seg_start
        t = np.dot(v, seg_dir)
        
        # Clamp 't' to strictly remain within the start/end bounds of the segment
        t_clamped = np.clip(t, 0, seg_len)
        closest_pt_on_seg = seg_start + t_clamped * seg_dir
        
        dist_to_seg = np.linalg.norm(pos - closest_pt_on_seg)
        
        # If this is the closest segment so far, calculate our pulling target
        if dist_to_seg < closest_dist:
            closest_dist = dist_to_seg
            t_target = np.clip(t_clamped + lookahead, 0, seg_len)
            target_pt = seg_start + t_target * seg_dir
            
            # If the lookahead pushes us to the exact end of the segment, 
            # smoothly snap to the next waypoint to round the corner.
            if t_target == seg_len and i < len(path) - 2:
                target_pt = path[i+1]
                
    return target_pt

def get_closest_point_on_rect(pos, rect):
    """Mathematical utility to find the nearest geometric point on a rectangular wall (AABB)."""
    rx, ry, rw, rh = rect
    cx = np.clip(pos[0], rx, rx + rw)
    cy = np.clip(pos[1], ry, ry + rh)
    return np.array([cx, cy])

# ==========================================
# 2. CONTINUOUS-TIME DYNAMICS (ODE + B-SPLINE RPV)
# ==========================================
def continuous_multi_agent_dynamics(t, state_vector, agents, obstacles):
    """
    The Core ODE System passed to SciPy's solve_ivp.
    Calculates instantaneous derivative (dx/dt, dy/dt, dW/dt) at continuous time 't'.
    State Vector 'y' format: [x1, y1, W1, x2, y2, W2, ...]
    Where 'W' is the Deadlock Evasion Weight (0.0 to 1.0).
    """
    num_agents = len(agents)
    dstate_dt = np.zeros_like(state_vector)
    
    # Unpack continuous state variables
    positions = state_vector[0::3]
    positions_y = state_vector[1::3]
    weights = state_vector[2::3]
    
    for i, agent in enumerate(agents):
        p_i = np.array([positions[i], positions_y[i]])
        W_i = weights[i] 
        
        dist_to_final_goal = np.linalg.norm(agent.goal - p_i)
        
        # ---------------------------------------------------------
        # PARKING BRAKE
        # ---------------------------------------------------------
        if dist_to_final_goal <= GOAL_TOLERANCE:
            # Velocity = 0.0, and actively decay any remaining evasion weight to 0.0
            dstate_dt[i*3 : i*3 + 3] = [0.0, 0.0, -2.0 * W_i] 
            continue
            
        # ---------------------------------------------------------
        # ZENO'S PARADOX FIX (Target Speed)
        # ---------------------------------------------------------
        # A tight 0.2m arrival radius and a hard 0.5m/s floor ensures the agent 
        # decisively crosses the finish line rather than asymptotically crawling.
        v_max = 1.5
        arrival_radius = 0.2 
        if dist_to_final_goal < arrival_radius:
            target_speed = max(0.5, v_max * (dist_to_final_goal / arrival_radius))
        else:
            target_speed = v_max
            
        # ---------------------------------------------------------
        # PHASE 1: EXACT RRT* NOMINAL TARGET (Attraction)
        # ---------------------------------------------------------
        P0 = p_i
        P2 = get_lookahead_target(P0, agent.global_path, lookahead=0.8)
        
        dir_to_P2 = P2 - P0
        dist_P2 = np.linalg.norm(dir_to_P2)
        dir_norm = dir_to_P2 / dist_P2 if dist_P2 > 0 else np.zeros(2)
        
        # Nominal velocity vector tracking the RRT* line segment
        v_att = dir_norm * target_speed
        
        # ---------------------------------------------------------
        # PHASE 2: CUBIC APF SAFETY BOUNDARIES (Repulsion)
        # ---------------------------------------------------------
        # Hyper-stiff mathematical forces that approach infinity as distance -> 0.
        v_rep_agent = np.zeros(2)
        v_rep_wall = np.zeros(2)
        d_safe = ROBOT_RADIUS + 0.3 
        
        # Agent-to-Agent force (Dynamic)
        for j in range(num_agents):
            if i == j: continue
            p_j = np.array([positions[j], positions_y[j]])
            dist_ij = np.linalg.norm(p_i - p_j)
            if 0.01 < dist_ij < d_safe:
                rep_mag = 5.0 * ((1.0/dist_ij - 1.0/d_safe)**3) * (1.0/(dist_ij**2))
                v_rep_agent += rep_mag * ((p_i - p_j) / dist_ij)
                
        # Agent-to-Wall force (Static)
        for obs in obstacles:
            closest_pt = get_closest_point_on_rect(p_i, obs)
            dist_wall = np.linalg.norm(p_i - closest_pt)
            if 0.01 < dist_wall < (ROBOT_RADIUS + 0.05):
                rep_mag = 8.0 * ((1.0/dist_wall - 1.0/(ROBOT_RADIUS + 0.05))**3) * (1.0/(dist_wall**2))
                v_rep_wall += rep_mag * ((p_i - closest_pt) / dist_wall)
                
        # ---------------------------------------------------------
        # PHASE 3: DIFFERENTIAL DEADLOCK EQUATION (ODE for Weight)
        # ---------------------------------------------------------
        # Project our forces forward. If progress is negative, we are deadlocked.
        forward_progress = np.dot(v_att + v_rep_agent, dir_norm)
        
        # THE ORBITING FIX: Disable evasion if within 0.5m of the goal.
        # This prevents continuous RPV noise from forcing the robot into a circular orbit.
        if dist_to_final_goal < 0.5:
            W_target = 0.0
        else:
            # Logistic Sigmoid maps progress into a smooth 0.0 -> 1.0 target weight
            W_target = 1.0 / (1.0 + np.exp(15.0 * (forward_progress - 0.2)))
        
        # Asymmetric Snap-Back ODE:
        # Spike weight extremely fast (alpha=10) if a deadlock occurs.
        # Snap-back smoothly (alpha=3) once the path clears to regain optimal RRT* tracking.
        if W_target > W_i:
            dW_dt = 10.0 * (W_target - W_i)  
        else:
            dW_dt = 3.0 * (W_target - W_i)   
            
        # ---------------------------------------------------------
        # PHASE 4: LOCAL B-SPLINE RPV PULL (Symmetry Breaking)
        # ---------------------------------------------------------
        # 1. Continuous Random Angle (theta)
        # Use continuous simulation time 't' to drift the angle across the full 360 degrees.
        # This guarantees the robot eventually finds a completely free evasion path.
        theta = agent.random_base_angle + (agent.random_drift_rate * t)
        
        # 2. Formulate the B-Spline Control Point (P1)
        # Nominal P1 sits strictly on the line segment between P0 (Agent) and P2 (RRT* Target).
        P1_nominal = P0 + (dir_norm * (target_speed * 0.5)) 
        
        # Pull P1 dynamically in the randomized direction, strictly scaled by ODE weight W_i.
        pull_vector = np.array([np.cos(theta), np.sin(theta)]) * 3.0 * W_i
        P1_shifted = P1_nominal + pull_vector
        
        # 3. Derive Agent Velocity from the B-Spline Tangent
        # For a Quadratic Bezier/B-Spline, the starting tangent velocity is 2*(P1 - P0).
        v_spline_tangent = 2.0 * (P1_shifted - P0)
        
        # 4. Absolute Safety Guarantee
        # APF Wall/Agent repulsions are added LAST. Even if the shifted B-Spline tries 
        # to pull the robot into a wall, the hyper-stiff cubic APF mathematically overpowers it.
        v_final = v_spline_tangent + v_rep_agent + v_rep_wall
        
        # Clamp to maximum physically allowed speed
        speed = np.linalg.norm(v_final)
        if speed > target_speed:
            v_final = (v_final / speed) * target_speed
            
        # Write state derivatives back to the solver
        dstate_dt[i*3 : i*3 + 3] = [v_final[0], v_final[1], dW_dt]
        
    return dstate_dt

# ==========================================
# 3. SIMULATION SETUP & EXECUTION
# ==========================================
class DynamicAgent:
    def __init__(self, id, start, goal, color):
        self.id = id
        self.pos = np.array(start, dtype=float)
        self.goal = np.array(goal, dtype=float)
        self.color = color
        self.global_path = None
        
        # --- DECENTRALIZED SYMMETRY BREAKERS ---
        # Agents do not rely on central IDs. Each independently selects a random 
        # base angle and drift rate to ensure perfectly symmetric deadlocks are broken.
        self.random_base_angle = np.random.uniform(0, 2*np.pi) 
        self.random_drift_rate = np.random.uniform(-1.0, 1.0) 

def run_continuous_simulation(scenario):
    """Configures the environment, solves the ODE, and plots the results sequentially."""
    
    # Map Initialization based on argparse input
    if scenario == "corridor":
        obstacles = [
            (4.8, 5.75, 0.4, 6.25), (4.8, -2.0, 0.4, 6.25),   
            (-2.0, 11.0, 14.0, 0.5), (-2.0, -1.5, 14.0, 0.5),  
            (-1.5, -1.5, 0.5, 13.0), (11.0, -1.5, 0.5, 13.0)   
        ]
        agents = [
            DynamicAgent(1, [0.0, 5.0], [10.0, 5.0], 'blue'),
            DynamicAgent(2, [10.0, 5.0], [0.0, 5.0], 'red')
        ]
    elif scenario == "maze":
        obstacles = [
            (-2.0, 7.0, 14.0, 1.0), (-2.0, 2.0, 14.0, 1.0),   
            (3.0, 4.5, 1.5, 2.5), (6.0, 3.0, 1.5, 2.5),     
        ]
        agents = [
            DynamicAgent(1, [0.0, 5.0], [10.0, 5.0], 'blue'),
            DynamicAgent(2, [10.0, 5.0], [0.0, 5.0], 'red')
        ]
    else: # Default to intersection
        obstacles = [
            (-2.0, -2.0, 6.0, 6.0), (-2.0, 6.0, 6.0, 6.0),   
            (6.0, -2.0, 6.0, 6.0), (6.0, 6.0, 6.0, 6.0),    
        ]
        agents = [
            DynamicAgent(1, [0.0, 5.0], [10.0, 5.0], 'blue'),
            DynamicAgent(2, [10.0, 5.0], [0.0, 5.0], 'red'),
            DynamicAgent(3, [5.0, 0.0], [5.0, 10.0], 'green'),
            DynamicAgent(4, [5.0, 10.0], [5.0, 0.0], 'purple')
        ]
        
    print(f"Computing Exact RRT* Paths for '{scenario.upper()}'...")
    rrt_obstacles = [(x - ROBOT_RADIUS, y - ROBOT_RADIUS, w + (2 * ROBOT_RADIUS), h + (2 * ROBOT_RADIUS)) for (x, y, w, h) in obstacles]

    for a in agents:
        rrt = RRTStarBridge(a.pos, a.goal, rrt_obstacles, [-2, 12])
        raw_path = rrt.plan()
        if raw_path is None: raw_path = np.array([a.pos, a.goal])
        # Direct loading of rigid RRT* segments ensures pure asymptotic adherence
        a.global_path = raw_path

    # Construct continuous starting state vector
    initial_state = []
    for a in agents:
        initial_state.extend([a.pos[0], a.pos[1], 0.0]) 
        
    def termination_event(t, y):
        """Halts the ODE solver exactly when all agents reach their goals."""
        distances = []
        for i, a in enumerate(agents):
            pos = np.array([y[i*3], y[i*3+1]])
            distances.append(np.linalg.norm(pos - a.goal))
        return max(distances) - GOAL_TOLERANCE
    termination_event.terminal = True
    termination_event.direction = -1

    print("Running True Continuous-Time ODE Solver (solve_ivp)...")
    T_MAX = 40.0 # Safety cap on simulation time
    
    sol = solve_ivp(
        fun=lambda t, y: continuous_multi_agent_dynamics(t, y, agents, obstacles),
        t_span=(0, T_MAX),
        y0=initial_state,
        events=termination_event,
        dense_output=True, 
        max_step=0.1 
    )
    
    print(f"ODE Solver finished at t = {sol.t[-1]:.2f} seconds.")

    # ==========================================
    # 4. RENDER ANIMATION & PLOTS (SEQUENTIALLY)
    # ==========================================
    print("Preparing Visuals...")
    t_frames = np.arange(0, sol.t[-1], 0.05)
    y_frames = sol.sol(t_frames)
    
    # --- FIGURE 1: THE ANIMATION ---
    fig, ax = plt.subplots(figsize=(8, 8)) 
    for (ox, oy, w, h) in obstacles:
        ax.add_patch(patches.Rectangle((ox, oy), w, h, color='black', alpha=0.8))
        
    for a in agents:
        # Draw rigid RRT* lines
        ax.plot(a.global_path[:,0], a.global_path[:,1], color=a.color, linestyle=':', alpha=0.5, lw=2)
        ax.scatter(a.goal[0], a.goal[1], marker='*', s=300, color='yellow', edgecolors=a.color, zorder=5)

    ax.set_title(f"Continuous ODE (B-Spline RPV) - {scenario.capitalize()}", fontsize=14)
    ax.set_xlim(-1.0, 11.0)
    ax.set_ylim(-1.0, 11.0)
    ax.set_aspect('equal')
    plt.grid(True, linestyle='--', alpha=0.6)

    mode_text = ax.text(0.5, 0.95, '', transform=ax.transAxes, ha='center', fontsize=12, bbox=dict(facecolor='white', alpha=0.8))
    
    lines, heads = [], []
    for a in agents:
        line, = ax.plot([], [], color=a.color, lw=2.5, zorder=3)
        head, = ax.plot([], [], 'o', color=a.color, markersize=10, markeredgecolor='white', zorder=5)
        lines.append(line)
        heads.append(head)

    def update(frame_idx):
        for i, a in enumerate(agents):
            hist_x = y_frames[i*3][:frame_idx+1]
            hist_y = y_frames[i*3+1][:frame_idx+1]
            lines[i].set_data(hist_x, hist_y)
            heads[i].set_data([hist_x[-1]], [hist_y[-1]])

        # Dynamically display the physical distance to the goal
        distances = []
        for i, a in enumerate(agents):
            current_pos = np.array([y_frames[i*3][frame_idx], y_frames[i*3+1][frame_idx]])
            dist = np.linalg.norm(current_pos - a.goal)
            distances.append(dist)
            
        strs = [f"A{i+1}: {d:.2f}m" for i, d in enumerate(distances)]
        mode_text.set_text(f"Time: {t_frames[frame_idx]:.2f}s | " + " | ".join(strs))
        return lines + heads + [mode_text]

    ani = FuncAnimation(fig, update, frames=len(t_frames), blit=False, interval=50, repeat=False)
    ani.save(f'output-continuous/{scenario}_simulation.mp4', writer='ffmpeg', fps=20) # Save the animation as mp4
    print("Displaying Animation... (Close the window to view the Error Plot)")
    # FIRST SHOW CALL: Blocks script until the user closes the animation window
    plt.show()

    # --- FIGURE 2: THE ERROR CONVERGENCE PLOT ---
    print("Calculating and Displaying Error Plot...")
    fig_error, ax_error = plt.subplots(figsize=(10, 5))
    
    for i, a in enumerate(agents):
        x_hist = y_frames[i*3]
        y_hist = y_frames[i*3+1]
        distances = [np.linalg.norm(np.array([x, y]) - a.goal) for x, y in zip(x_hist, y_hist)]
        ax_error.plot(t_frames, distances, label=f'Agent {a.id}', color=a.color, lw=2)
        
    ax_error.set_title(f"Continuous Distance to Goal ({scenario.capitalize()})", fontsize=14, fontweight='bold')
    ax_error.set_xlabel("Time (seconds)", fontsize=12)
    ax_error.set_ylabel("Distance to Goal (m)", fontsize=12)
    ax_error.grid(True, linestyle='--', alpha=0.6)
    ax_error.legend()
    
    plt.tight_layout()
    plt.savefig(f'output-continuous/distance_error_plot_{scenario}.png', dpi=300)
    # SECOND SHOW CALL: Displays the static distance graph
    plt.show()
    
    print(f"[{scenario.upper()}] Execution complete.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Multi-Agent Continuous APF Navigation")
    parser.add_argument('--map', type=str, choices=['corridor', 'intersection', 'maze'], 
                        default='intersection', help="Select the map scenario to run.")
    args = parser.parse_args()
    
    run_continuous_simulation(args.map)