import numpy as np
import scipy.interpolate as si
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.animation import FuncAnimation

from rrt_bridge import RRTStarBridge
from tube_bspline_short import TubeBSplineShort

# ==========================================
# GLOBAL CONFIGURATION
# ==========================================
# Single Source of Truth for robot physics to prevent hardcoding bugs
ROBOT_RADIUS = 0.35    
GOAL_TOLERANCE = 0.05  # Acceptable parking distance from exact goal coordinate

# ==========================================
# 2. RRT PATH SMOOTHER
# ==========================================
def smooth_global_path(path, num_points=100):
    """
    Takes the jagged, straight-line waypoints generated by the RRT* global planner
    and fits a B-spline curve through them to create a smooth, drivable trajectory.
    """
    clean_path = [path[0]]
    
    # Filter out duplicate or excessively close waypoints that cause matrix singularities
    # in the SciPy spline interpolation function.
    for pt in path[1:]:
        if np.linalg.norm(pt - clean_path[-1]) > 0.05:
            clean_path.append(pt)
    clean_path = np.array(clean_path)

    # Fallback Mechanism: If the path is too short (3 points or less), a cubic spline (k=3)
    # cannot mathematically be drawn. We default to simple linear interpolation instead.
    if len(clean_path) <= 3:
        dists = np.cumsum(np.linalg.norm(np.diff(clean_path, axis=0), axis=1))
        dists = np.insert(dists, 0, 0)
        if dists[-1] == 0: 
            return clean_path
        fx = si.interp1d(dists, clean_path[:,0], kind='linear')
        fy = si.interp1d(dists, clean_path[:,1], kind='linear')
        sample_dists = np.linspace(0, dists[-1], num_points)
        return np.column_stack((fx(sample_dists), fy(sample_dists)))

    # Standard B-spline smoothing: Generates a 3rd-degree (k=3) continuous curve
    # sampled at exactly 'num_points' to provide dense waypoints for the local planner.
    
    # TIGHTER SPLINE SMOOTHING & ANCHORING
    # Reduced s=2.0 to s=0.5 to prevent massive looping curves that overshoot the goal.
    tck, u = si.splprep([clean_path[:,0], clean_path[:,1]], s=0.5, k=3)
    u_new = np.linspace(0, 1.0, num_points)
    x_smooth, y_smooth = si.splev(u_new, tck)
    
    smoothed_path = np.column_stack((x_smooth, y_smooth))
    
    # Anchor the first and last points to absolutely prevent 'Goal Drift'
    smoothed_path[0] = clean_path[0]
    smoothed_path[-1] = clean_path[-1]
    return smoothed_path

# ==========================================
# 3. 2-MODE HYBRID APF (Pure State Machine)
# ==========================================
class TwoModeAPF:
    """
    A Hybrid Artificial Potential Field that governs the high-level decision making.
    It evaluates environmental forces to detect deadlocks, and switches between a 
    Stable Mode (Gradient Descent) and a Chaos Mode (Stochastic Symmetry Breaking).
    """
    def __init__(self, k_att=2.0, k_rep_agent=5.0, k_rep_wall=8.0, r_base=ROBOT_RADIUS, kappa=0.5, deadlock_tol=0.2):
        # Force Coefficients
        self.k_att = k_att               # Attraction strength toward the goal
        self.k_rep_agent = k_rep_agent   # Repulsion strength from other agents
        self.k_rep_wall = k_rep_wall     # Repulsion strength from walls/obstacles
        
        # Dynamic Safety Tube parameters
        self.r_base = r_base             # Base radius of the robot (tied to global config)
        self.kappa = kappa               # Velocity-dependent radius scaling factor
        
        # Deadlock Detection
        self.deadlock_tol = deadlock_tol # Threshold for detecting a loss of forward progress
        self.d_safe_wall = 0.6           # The physical size of the wall's repulsive forcefield

    def get_closest_point_on_rect(self, pos, rect):
        """Calculates the mathematically nearest geometric point on an Axis-Aligned Bounding Box (AABB)"""
        rx, ry, rw, rh = rect
        cx = np.clip(pos[0], rx, rx + rw)
        cy = np.clip(pos[1], ry, ry + rh)
        return np.array([cx, cy])

    def get_desired_velocity(self, agent, p_target, other_agents, obstacles):
        p_i = agent.pos

        # DECOUPLE STEERING FROM BRAKING
        # dist_to_final_goal strictly controls the brakes (distance to absolute final target)
        dist_to_final_goal = np.linalg.norm(agent.goal - p_i)

        ## ---------------------------------------------------------
        # PHASE 1: ATTRACTION & PERFECT PARKING
        # ---------------------------------------------------------
        # 1. Engage brakes if within Goal Tolerance. No teleporting.
        if dist_to_final_goal <= GOAL_TOLERANCE:
            return np.zeros(2)

        # 2. Linear damping: slow down dynamically as we approach the target
        # This acts as a kinematic brake to prevent overshooting the final coordinate.
        v_max = 1.5
        arrival_radius = 1.0
        target_speed = v_max * (dist_to_final_goal / arrival_radius) if dist_to_final_goal < arrival_radius else v_max
        
        # 3. GENERALIZED STEERING (No Map-Specific Hardcoding)
        # We always steer toward the lookahead waypoint (p_target). 
        # Because the lookahead function clamps to the end of the array, 
        # p_target naturally becomes the absolute goal at the end of the journey.
        dir_to_waypoint = p_target - p_i
        dist_to_waypoint = np.linalg.norm(dir_to_waypoint)
        
        # Steer towards waypoint at the speed dictated by the final goal distance
        dir_target_norm = dir_to_waypoint / dist_to_waypoint if dist_to_waypoint > 0 else np.zeros(2)
        v_att = dir_target_norm * target_speed

        # ---------------------------------------------------------
        # PHASE 2: HYPER-STIFF CUBIC REPULSION
        # ---------------------------------------------------------
        # Calculate dynamic safety distance based on the agent's previous step speed
        current_speed = 0.0
        if len(agent.history) > 1:
            current_speed = np.linalg.norm(agent.history[-1] - agent.history[-2]) / 0.5
        dynamic_d_safe = self.r_base + (self.kappa * current_speed)

        v_rep = np.zeros(2)
        
        # Agent-to-Agent Repulsion (Cubic formulation)
        # Guarantees mathematical divergence (infinite repulsion) as agents approach collision.
        for other in other_agents:
            dist_ij = np.linalg.norm(p_i - other.pos)
            if 0.01 < dist_ij < dynamic_d_safe:
                rep_mag = self.k_rep_agent * ((1.0/dist_ij - 1.0/dynamic_d_safe)**3) * (1.0/(dist_ij**2))
                v_rep += rep_mag * ((p_i - other.pos) / dist_ij)

        # Agent-to-Wall Repulsion (Cubic formulation)
        for obs in obstacles:
            closest_pt = self.get_closest_point_on_rect(p_i, obs)
            dist_wall = np.linalg.norm(p_i - closest_pt)
            if 0.01 < dist_wall < self.d_safe_wall:
                rep_mag = self.k_rep_wall * ((1.0/dist_wall - 1.0/self.d_safe_wall)**3) * (1.0/(dist_wall**2))
                v_rep += rep_mag * ((p_i - closest_pt) / dist_wall)

        # THE "PARKING PANIC" FIX
        # Calculate theoretical progress using UN-DAMPED attraction.
        # This isolates environmental resistance (walls/agents) from deliberate parking brakes.
        v_att_undamped = dir_target_norm * v_max
        theoretical_forward_progress = np.dot(v_att_undamped + v_rep, dir_target_norm)

        # ---------------------------------------------------------
        # PHASE 3: PURE GEOMETRIC STATE MACHINE
        # ---------------------------------------------------------
        if agent.mode == 1:
            # TRIGGER CHAOS: If forward progress drops below tolerance, we are trapped.
            if theoretical_forward_progress < self.deadlock_tol:
                agent.mode = 2
                agent.rand_angle = np.random.uniform(0, 2 * np.pi) 
                
        elif agent.mode == 2:
            # BULLETPROOF HYSTERESIS
            # Max possible progress is 1.5. We demand > 1.4 to exit Chaos.
            # The agent MUST bounce until it is completely clear of the obstacle's
            # repulsive forcefield to prevent rapid ping-ponging at corners.
            if theoretical_forward_progress > 1.4:
                agent.mode = 1

        # ---------------------------------------------------------
        # PHASE 4: VELOCITY CALCULATION
        # ---------------------------------------------------------
        v_final = np.zeros(2)

        if agent.mode == 1:
            # Mode 1 (Stable): Standard APF Gradient Tracking
            v_final = v_att + v_rep
        else:
            # Mode 2 (Chaos): Stochastic Symmetry Breaking
            # Injects random directional velocity while maintaining wall repulsion safety
            agent.rand_angle += np.random.uniform(-0.5, 0.5)
            rand_mag = np.random.uniform(2.0, 4.0) 
            v_rand = np.array([np.cos(agent.rand_angle), np.sin(agent.rand_angle)]) * rand_mag
            v_final = v_rand + v_rep
            
        # Ensure we never exceed our dynamically damped target speed limit
        speed = np.linalg.norm(v_final)
        if speed > target_speed:
            v_final = (v_final / speed) * target_speed

        return v_final

# ==========================================
# 4. SIMULATION EXECUTION & ANIMATION
# ==========================================
class DynamicAgent:
    def __init__(self, id, start, goal, color):
        self.id = id
        self.pos = np.array(start, dtype=float)
        self.goal = np.array(goal, dtype=float)
        self.color = color
        self.global_path = None
        self.path_idx = 1 
        self.history = [self.pos.copy()]
        
        self.mode = 1           
        self.rand_angle = 0.0 
        self.mode_history = [self.mode] 

def get_current_target(agent):
    """
    Dynamic Lookahead Algorithm (Pure Pursuit style).
    Always searches for the closest point on the global path relative to the agent's 
    CURRENT physical position, then looks slightly ahead. This guarantees recovery 
    even if Chaos Mode blasts the agent far away from its expected route.
    """
    dists = np.linalg.norm(agent.global_path - agent.pos, axis=1)
    closest_idx = np.argmin(dists)
    
    # Ensure the agent tightly tracks the safe RRT* centerline
    # through the door and avoids cutting into the wall corners.
    target_idx = min(closest_idx + 3, len(agent.global_path) - 1)
    return agent.global_path[target_idx]

def run_simulation():
    # THE STRESS TEST: 1.5m Corridor
    obstacles = [
        (4.8, 5.75, 0.4, 6.25),   # Top wall pulled down
        (4.8, -2.0, 0.4, 6.25),   # Bottom wall pulled up
        (-2.0, 11.0, 14.0, 0.5),  
        (-2.0, -1.5, 14.0, 0.5),  
        (-1.5, -1.5, 0.5, 13.0),  
        (11.0, -1.5, 0.5, 13.0)   
    ]
    
    a1 = DynamicAgent(1, [0.0, 5.0], [10.0, 5.0], 'blue')
    a2 = DynamicAgent(2, [10.0, 5.0], [0.0, 5.0], 'red')
    agents = [a1, a2]
    
    print("Computing Initial RRT* Bridge Paths...")

    # MINKOWSKI SUM
    rrt_obstacles = [
        (x - ROBOT_RADIUS, y - ROBOT_RADIUS, w + (2 * ROBOT_RADIUS), h + (2 * ROBOT_RADIUS)) 
        for (x, y, w, h) in obstacles
    ]

    for a in agents:
        # Pass C-space obstacles to the global planner
        rrt = RRTStarBridge(a.pos, a.goal, rrt_obstacles, [-2, 12])
        raw_path = rrt.plan()
        if raw_path is None:
            raw_path = np.array([a.pos, a.goal])
        # Smooth the raw RRT* waypoints
        a.global_path = smooth_global_path(raw_path, num_points=100)

    print("Running Background Simulation...")
    apf = TwoModeAPF(r_base=ROBOT_RADIUS) # Pass global robot physics here too
    dt = 0.5 
    
    # Simulation Receding Horizon Loop
    for step in range(800): 
        
        # EXACT TERMINATION MATCH
        # Evaluate if the entire system has reached its goal state exactly at the 
        # GOAL_TOLERANCE margin.
        all_parked = all(np.linalg.norm(a.pos - a.goal) <= GOAL_TOLERANCE for a in agents)
        
        # EARLY TERMINATION TRIGGER
        # Stop simulating the moment both agents are perfectly parked at their targets.
        if all_parked:
            print(f"Simulation completed successfully! Both agents parked at step {step}.")
            break
            
        for i, agent in enumerate(agents):
            dist_to_final_goal = np.linalg.norm(agent.pos - agent.goal)
            
            # If the robot is within tolerance, just engage the parking brake. 
            # It retains its true kinematic coordinate without faking the position.
            if dist_to_final_goal <= GOAL_TOLERANCE:
                agent.history.append(agent.pos.copy())
                agent.mode_history.append(1)
                continue 
                
            # Keep ALL agents in the obstacle array. A parked agent represents a solid,
            # unmoving physical robot that the remaining agents must navigate around.
            other_agents = [a for a in agents if a.id != agent.id]
            
            target_wp = get_current_target(agent)
            
            # Calculate ideal APF force
            v_des = apf.get_desired_velocity(agent, target_wp, other_agents, obstacles)
            
            # By-pass the B-spline entirely for perfect 0.0 margin zero-velocity stops
            if np.linalg.norm(v_des) == 0:
                agent.history.append(agent.pos.copy())
                agent.mode_history.append(1)
                continue
                
            # Feed the APF velocity into the Tube B-Spline optimizer for collision-safe smoothing
            # Ensure the Tube uses the exact same physical radius!
            short_term_goal = agent.pos + (v_des * dt * 2.0) 
            planner = TubeBSplineShort(agent.pos, short_term_goal, obstacles, r0=ROBOT_RADIUS)
            safe_traj = planner.plan()
            
            # Extract the actual safe step from the B-spline path execution
            agent.pos = safe_traj[1] 
            agent.history.append(agent.pos.copy())
            agent.mode_history.append(agent.mode)

    print("Rendering Animation...")
    fig, ax = plt.subplots(figsize=(8, 8)) 
    
    # Draw physical obstacles
    for (ox, oy, w, h) in obstacles[:2]:
        ax.add_patch(patches.Rectangle((ox, oy), w, h, color='black', alpha=0.8))
        
    # Draw paths and target stars
    for a in agents:
        ax.plot(a.global_path[:,0], a.global_path[:,1], color=a.color, linestyle=':', alpha=0.3)
        ax.scatter(a.history[0][0], a.history[0][1], marker='o', s=100, color=a.color, edgecolors='black', zorder=4)
        
        # The star is drawn at `a.goal`
        ax.scatter(a.goal[0], a.goal[1], marker='*', s=300, color='yellow', edgecolors=a.color, linewidths=2, zorder=5)

    ax.set_title("Stochastic Symmetry Breaking: 2-Mode Hybrid APF", fontsize=14)
    ax.set_xlim(-1.0, 11.0)
    ax.set_ylim(-1.0, 11.0)
    ax.set_aspect('equal')
    plt.grid(True, linestyle='--', alpha=0.6)

    # Dynamic text box for tracking mode changes
    mode_text = ax.text(0.5, 0.95, '', transform=ax.transAxes, ha='center', fontsize=12, 
                        bbox=dict(facecolor='white', alpha=0.8, edgecolor='black'), zorder=10)
    
    # Setup animation objects
    lines = []
    heads = []
    for a in agents:
        line, = ax.plot([], [], color=a.color, lw=2.5, zorder=3)
        head, = ax.plot([], [], 'o', color=a.color, markersize=10, markeredgecolor='white', zorder=5)
        lines.append(line)
        heads.append(head)

    def update(frame):
        for i, a in enumerate(agents):
            hist = np.array(a.history[:frame+1])
            lines[i].set_data(hist[:, 0], hist[:, 1])
            heads[i].set_data([hist[-1, 0]], [hist[-1, 1]])

        m1_str = "Chaos" if agents[0].mode_history[frame] == 2 else "Stable"
        m2_str = "Chaos" if agents[1].mode_history[frame] == 2 else "Stable"
        mode_text.set_text(f"Step: {frame} | Agent 1: {m1_str} | Agent 2: {m2_str}")
        return lines + heads + [mode_text]

    max_frames = max(len(a.history) for a in agents)
    ani = FuncAnimation(fig, update, frames=max_frames, blit=False, interval=100, repeat=False)
    
    plt.show()

if __name__ == "__main__":
    run_simulation()